pipeline {
    agent {
        docker {
            image 'node:18'
            args '-u root'
            reuseNode true
        }
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage("Install dependencies") {
            steps {
                dir('Jenkins-Student-Registry-App-Docker') {
                    sh 'npm install'
                }
            }
        }
        stage("Run tests") {
            steps {
                dir('Jenkins-Student-Registry-App-Docker') {
                    sh 'npm test'
                }
            }
        }
    }
}